// Compile the generated atlas into one flash-only RGB565 table and web tiles.
const fs = require('node:fs');
const path = require('node:path');
const sharp = require(process.env.WUW_SHARP || 'sharp');
const root = path.resolve(__dirname, '..');
async function main() {
  const inputs = process.argv.slice(2);
  if (inputs.length !== 3) throw new Error('Usage: node tools/build_game_art.cjs <shrine.png> <thorn.png> <tendril.png>');
  const out = path.join(root, 'site/game-preview/art');
  fs.mkdirSync(out, {recursive:true});
  const words = [], urls = [];
  for (const [atlas, input] of inputs.entries()) {
  const meta = await sharp(input).metadata();
  if (meta.width !== meta.height) throw new Error('Expected square 4x4 atlas');
  const cell = meta.width / 4;
  // Generated sheets have slightly uneven row boundaries; exclude the separators.
  const rows = atlas === 1 ? [0,310,600,897,1222].map(n=>Math.round(n*meta.height/1254)) :
    atlas === 2 ? [0,302,598,905,1254].map(n=>Math.round(n*meta.height/1254)) :
    [0,1,2,3,4].map(n=>Math.round(n*cell));
  for (let tile = 0; tile < 16; tile++) {
    const col=tile%4,row=Math.floor(tile/4),inset=atlas?4:0,left=Math.round(col*cell)+inset,top=rows[row]+inset;
    const crop = sharp(input).extract({left,top,width:Math.round((col+1)*cell)-inset-left,height:rows[row+1]-inset-top});
    const raw = await crop.resize(64,64).ensureAlpha().raw().toBuffer();
    for (let p=0;p<raw.length;p+=4) {
      if (tile < 8 && Math.max(raw[p],raw[p+1],raw[p+2]) < 35) raw[p+3]=0;
    }
    const pixels = sharp(raw, {raw:{width:64,height:64,channels:4}});
    const png=await pixels.clone().png().toBuffer();
    fs.writeFileSync(path.join(out, `tile-${atlas*16+tile}.png`),png);
    urls.push('data:image/png;base64,'+png.toString('base64'));
    const small = await pixels.clone().resize(32,32,{kernel:'nearest'}).raw().toBuffer();
    for (let p=0;p<small.length;p+=4) {
      const rgb=((small[p]>>3)<<11)|((small[p+1]>>2)<<5)|(small[p+2]>>3);
      words.push(tile<8&&small[p+3]<128?0:Math.max(1,rgb));
    }
  }
  }
  fs.writeFileSync(path.join(root,'assets/wuw-rpg-atlas.inc'), words.reduce((lines,n,i)=>lines+(i%12?'': '\n')+'0x'+n.toString(16).padStart(4,'0')+',','// Generated by tools/build_game_art.cjs\n'));
  fs.writeFileSync(path.join(out,'inline.js'),'// Generated for offline file preview.\nwindow.WuwArtUrls='+JSON.stringify(urls)+';\nwindow.dispatchEvent(new Event("wuw-art-ready"));\n');
  console.log('Compiled 48 tiles: 98304 bytes of flash; 64px PNGs for browser.');
}
main().catch(e=>{console.error(e);process.exit(1)});
