#!/usr/bin/env python3
"""Convert esp32-camera's OV5640 C register tables to Rust.

    python3 tools/gen_ov5640_regs.py

Reads rust/ov5640/vendor/ov5640_{regs,settings}.h, writes rust/ov5640/src/regs.rs.
"""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
VENDOR = ROOT / "rust" / "ov5640" / "vendor"
OUT = ROOT / "rust" / "ov5640" / "src" / "regs.rs"

def defines(text):
    return {m.group(1): int(m.group(2), 0)
            for m in re.finditer(r"^#define\s+(\w+)\s+(0x[0-9a-fA-F]+|\d+)\b", text, re.M)}

def value(tok, syms):
    tok = tok.strip()
    return int(tok, 0) if re.fullmatch(r"0x[0-9a-fA-F]+|\d+", tok) else syms[tok]

def parse(regs_h, settings_h):
    # REG_DLY / REGLIST_TAIL live in settings.h, register names in regs.h.
    syms = {**defines(regs_h), **defines(settings_h)}
    tables = {}
    for m in re.finditer(r"(\w+)\s*\[\s*\]\s*\[\s*2\s*\]\s*=\s*\{(.*?)\};", settings_h, re.S):
        name, body = m.group(1), re.sub(r"//[^\n]*", "", m.group(2))
        ops = []
        for a, b in re.findall(r"\{\s*(\w+)\s*,\s*(\w+)\s*\}", body):
            if a == "REGLIST_TAIL":
                break
            if a == "REG_DLY":
                ops.append(("D", value(b, syms), 0))
            else:
                ops.append(("W", value(a, syms), value(b, syms)))
        tables[name] = ops
    return tables

def emit(tables):
    out = ["// @generated by tools/gen_ov5640_regs.py from Espressif esp32-camera",
           "// (Apache-2.0). Do not edit by hand.",
           "#![allow(clippy::unreadable_literal)]", "", "use crate::Op;", ""]
    for name, ops in tables.items():
        out.append("pub const %s: &[Op] = &[" % name.upper())
        for kind, a, b in ops:
            out.append("    Op::DelayMs(%d)," % a if kind == "D"
                       else "    Op::Write(0x%04X, 0x%02X)," % (a, b))
        out.append("];")
        out.append("")
    return "\n".join(out)

def main():
    tables = parse((VENDOR / "ov5640_regs.h").read_text(),
                   (VENDOR / "ov5640_settings.h").read_text())
    OUT.write_text(emit(tables))
    print("wrote %s: %s" % (OUT.relative_to(ROOT),
          ", ".join("%s(%d)" % (k, len(v)) for k, v in tables.items())))

if __name__ == "__main__":
    main()
